name: Build and deploy

on:
  push:
    branches: [ master ]   # your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go (Hugo Modules need Go)
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Setup Hugo (extended)
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.151.0'
          extended: true

      # Helpful debug so you can see what's in the repo
      - name: Show repo layout
        run: |
          echo "== top =="
          ls -la
          echo "== content =="
          ls -la content || true
          echo "== config =="
          ls -la config.* || true

      # Generate go.sum and download the theme; also vendors it for reliability
      - name: Prepare modules
        run: |
          hugo mod tidy
          hugo mod vendor

      # Build with verbose logs so any error is obvious
      - name: Build
        run: hugo --minify -v

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
